import { getUserIdByEmail, createUser } from "../_db_d1/user";
import { createSession } from "../_sessions_kv/sessions";

export async function onRequestPost(context) {
  try {
    const request = context.request;
    const formData = await request.formData();
    const idToken = formData.get('credential'); // The JWT sent from the navbar code

    if (!idToken) {
      return new Response('Missing credential token', { status: 400 });
    }

    // 1. Verify the token with Google's public key endpoint
    // This makes sure the token hasn't expired and was actually generated by Google
    const verifyResponse = await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${idToken}`);
    
    if (!verifyResponse.ok) {
      return new Response('Invalid Google token verification failed', { status: 401 });
    }

    const payload = await verifyResponse.json();

    // 2. Security Check: Ensure the token was generated for YOUR app
    if (payload.aud !== context.env.GOOGLE_CLIENT_ID && payload.email_verified !== 'true') {
      console.error(`Audience mismatch: expected ${context.env.GOOGLE_CLIENT_ID}, got ${payload.aud}`);
      return new Response('Audience mismatch: Security validation failed', { status: 403 });
    }

    // You now have access to verified user parameters securely!
    // const email = payload.email;
    // const name = payload.name;
    // const googleUserId = payload.sub;
    let userId = await getUserIdByEmail(context.env.DB, payload.email);
    if (!userId) {
      // User doesn't exist, create a new user in the database
      console.log(`Creating new user.`);
      userId = await createUser(context.env.DB, { email: payload.email, name: payload.name, googleUserId: payload.sub });
    }

    // 3. Generate your application's session token 
    const {sessionId, ttl} = await createSession(context, userId)
  
    // 4. Send the Set-Cookie header and redirect them smoothly out of the API route
    return new Response(null, {
      status: 302,
      headers: {
        'Location': '/', // Where the user lands after successful navbar login
        'Set-Cookie': `minuet_session=${sessionId}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${ttl}`
      }
    });

  } catch (error) {
    return new Response(`Server Auth Error: ${error.message}`, { status: 500 });
  }
}