export async function onRequestPost(context) {
  try {
    const request = context.request;
    const formData = await request.formData();
    const idToken = formData.get('credential'); // The JWT sent from the navbar code

    if (!idToken) {
      return new Response('Missing credential token', { status: 400 });
    }

    // 1. Verify the token with Google's public key endpoint
    // This makes sure the token hasn't expired and was actually generated by Google
    const verifyResponse = await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${idToken}`);
    
    if (!verifyResponse.ok) {
      return new Response('Invalid Google token verification failed', { status: 401 });
    }

    const payload = await verifyResponse.json();

    // 2. Security Check: Ensure the token was generated for YOUR app
    if (payload.aud !== context.env.GOOGLE_CLIENT_ID) {
      return new Response('Audience mismatch: Security validation failed', { status: 403 });
    }

    // You now have access to verified user parameters securely!
    // const email = payload.email;
    // const name = payload.name;
    // const googleUserId = payload.sub;

    // 3. Generate your application's session token 
    // In a production app, you might encrypt this info or generate a session ID mapped to KV/Database
    const appSessionToken = btoa(JSON.stringify({ email: payload.email, expires: Date.now() + 604800000 }));

    // 4. Send the Set-Cookie header and redirect them smoothly out of the API route
    return new Response(null, {
      status: 302,
      headers: {
        'Location': '/dashboard', // Where the user lands after successful navbar login
        'Set-Cookie': `session=${appSessionToken}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=604800`
      }
    });

  } catch (error) {
    return new Response(`Server Auth Error: ${error.message}`, { status: 500 });
  }
}