import { getUserIdByEmail, createUser } from "../_db_d1/user";
import { createSession } from "../_sessions_kv/sessions";

export async function onRequestPost(context) {
  try {
    const request = context.request;
    const formData = await request.formData();
    const idToken = formData.get('credential'); // The JWT sent from the navbar code
    let return_code = 200; // default success code

    if (!idToken) {
      return new Response('Missing credential token', { status: 400 });
    }

    // 1. Verify the token with Google's public key endpoint
    // This makes sure the token hasn't expired and was actually generated by Google
    const verifyResponse = await fetch(`https://oauth2.googleapis.com/tokeninfo?id_token=${idToken}`);

    if (!verifyResponse.ok) {
      return new Response('Invalid Google token verification failed', { status: 401 });
    }

    const payload = await verifyResponse.json();

    // 2. Security Check: Ensure the token was generated for YOUR app
    if (payload.aud !== context.env.GOOGLE_CLIENT_ID || payload.email_verified !== 'true') {
      console.error(`Audience mismatch: expected ${context.env.GOOGLE_CLIENT_ID}, got ${payload.aud} and email_verified: ${payload.email_verified}`);
      return new Response('Audience mismatch: Security validation failed', { status: 403 });
    }

    // You now have access to verified user parameters securely!
    // const email = payload.email;
    // const name = payload.name;
    // const googleUserId = payload.sub;
    if (!payload.email || !payload.name || !payload.sub) {
      return new Response('Missing required user information from Google token', { status: 400 });
    }
    console.log('Verified Google user, signing in');

    let userId = await getUserIdByEmail(context.env.db, payload.email);
    if (!userId) {
      // User doesn't exist, create a new user in the database
      userId = await createUser(context.env.db, { email: payload.email, name: payload.name, googleUserId: payload.sub });
      console.log(`Created new user with ID: ${userId}`);
      return_code = 201; // Created
    }

    if (!userId) {
      return new Response('Failed to create or retrieve user', { status: 500 });
    }
    console.log(`User ID: ${userId}`);

    // 3. Generate your application's session token 
    const { sessionId, ttl } = await createSession(context, userId);
    if (!sessionId) {
      return new Response('Failed to create session', { status: 500 });
    }

    // 4. Send the Set-Cookie header and redirect them smoothly out of the API route
    return new Response(null, {
      status: return_code,
      headers: {
        'Set-Cookie': `minuet_session=${sessionId}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${ttl}`
      }
    });

  } catch (error) {
    return new Response(`Server Auth Error: ${error}`, { status: 500 });
  }
}